name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.1" # Adjust this to match your Ruby version
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle install

      - name: Setup database
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate

      - name: Precompile assets
        env:
          RAILS_ENV: production
          SECRET_KEY_BASE: dummy
        run: |
          bundle exec rails assets:precompile

      - name: Start Rails server in background
        run: |
          bundle exec rails server -d
          sleep 5 # Give the server some time to start

      - name: Generate static files
        run: |
          mkdir -p _site
          wget --convert-links --mirror --adjust-extension --no-parent --wait=2 --recursive --page-requisites --level=inf --no-host-directories --directory-prefix=_site http://127.0.0.1:3000/

      - name: Ensure fonts directory exists
        run: |
          mkdir -p _site/assets/fonts

      - name: Copy assets
        run: |
          cp -r public/assets/* _site/assets/ || true
          find public/assets -name "*.ttf" -exec cp {} _site/assets/fonts/ \; || true

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site # The folder containing your static files
          branch: gh-pages # The branch to deploy to
          clean: true # Automatically remove deleted files from the deployment branch
